### PR TITLE
updated map index page added header and footer

### PR DESCRIPTION
**Pull request by mashcode**
Hey, Updated the map index page but ran into what's sort of a blocker for UI development. The map won't display  within a "block" container. It's likely the embedded inline css within the cartodb map interface. So I will have to go into cartodb and see what's what. It may be just a matter of refactoring. Without a proper container element doing mobile interfaces or any interfaces quickly gets very snarly/gnarly.

The new map page now has a border. Hope that's ok.

### CODE REVIEW

**Comment by schmiani** [comment]
I tested the new page on your fork and for some reason the infowindows don't work, or not all of them! Do you have any idea why this might be? I guess it also has to do with the embedded css?

**Comment by mashcode** [comment]
I tested on iOS and WebKit chrome and safari and though hard to use on small screens the windows work

Marc

**Comment by mashcode** [comment]
Btw sometimes CSS gets cached in the browser from a previous session

Marc

**Comment by schmiani** [comment]
I am testing it in the browser on my desktop and figured out that there is
an offset between the location of the marker and the location where the
infobox is displayed! Both in Chrome and Firefox. Can you check on a
computer with mouse? I am guessing that with a touch screen it's hard to
realize that there is an offset. So strange though! I have to move slightly
to the right and below the marker to activate the infowindow...

**Comment by mashcode** [comment]
Hi Anita, I checked with a mouse and we're good. Everything works.

I see Twitter and Fb links on the old home page on mobile but not on
desktop? Are they injected by cartodb? We probably should take them out of
cartodb if that's the case

Marc

email marc@marcshifflett.com | mobile 917-570-7079

**Comment by schmiani** [comment]
OK, I pulled it but it's still a problem. It's only noticeable if you zoom in and try to click on one of the smaller markers.

About the Twitter and Facbook links, on the old page on desktop, there was a "share" icon on the top right that would let your share on Twitter and FB (on mobile it just looked different). But this was a feature of using the iframe. Now that we use the cartoDB.js API it's not there anymore anyway. We will have to check if the API allows to add that feature or else we will have to add it ourselves.

**Comment by schmiani** [comment]
BTW, the iframe is still on my personal homepage: http://www.anitaschmid.com/datascience/

And also, you can compare the infobox behavior to the public map on cartoDB directly: http://cdb.io/SBLKh6

**Comment by mashcode** [comment]
I will add a TODO.md so we can start to track bugs and changes.

The container bug I've experienced is probably worthy of checking if it's
an issue at cartodb

On Jun 6, 2014, at 5:09 PM, Anita Schmid notifications@github.com wrote:

BTW, the iframe is still on my personal homepage:
http://www.anitaschmid.com/datascience/

And also, you can compare the infobox behavior to the public map on cartoDB
directly: http://cdb.io/SBLKh6

**Pull request merged**
