### PR TITLE
Added ajax-loader gif to replace map. I know probably a little too subtl...

### PR DESCRIPTION
**Pull request by mashcode**
...e. Did some tweaking to the info box font sizes and weights

Please test this one out. We can can the loader gif to something different or more prominent

### CODE REVIEW

**Comment by schmiani** [comment]
The font in the infowindows looks very small with this change, probably hard to read for people with vision problems! Can we leave that as is?

**Comment by mashcode** [comment]
Is this better?

**Comment by mashcode** [comment]
Hey Anita, I also added the first iteration of the collapsible filter bar. It can be seen in /dev/mobile. Obviously still needs some finessing. In the meantime can we review to make sure the labels are accurate/concise. Need more eyes on it.

The medicine dispensing filter is a weird one. Was thinking the most elegant solution would be to simply have a yes [ ] checkbox. Who is going search for day care that doesn't dispense medicine? Is there a use-case?

**Comment by schmiani** [comment]
Yes, looks much better! And yes, the medicine filter should absolutely be a checkbox! I agree that nobody will search specifically for places that cannot administer medicine. That will save some space too! The collapsible filters on the dev site look awesome too!

**Pull request merged**
