### PR TITLE
added mailto link to navigation that launches external mail app

### PR DESCRIPTION
**Pull request by mashcode**
investigating a tooltip scheme and appropriate mail icon

### CODE REVIEW

**Comment by schmiani** [comment]
Hi Marc! I think the mailto icon is not quite clear to everyone, should we just say "Contact Us"? And the medicine filter is confusing I think. One might think "reset" will reset everything. Is it hard to do a checkbox? Or an on/off toggle or on/off slider? Thanks!

**Comment by mashcode** [comment]
On Jul 21, 2014, at 9:59 PM, Anita Schmid notifications@github.com wrote:

Hi Marc! I think the mailto icon is not quite clear to everyone, should we
just say "Contact Us"?

Sure, Im hunting around for a better icon. The one I'm using is a pretty
standard though but more often used to prompt multiple services. Just
realized that we also have the addthis module available.

Icons are both space efficient and communicate effectively to non english
speakers. The UI kit I'm using has tooltips but they are not firing because
there's are conflict with the navigation pseudo elements.

And the medicine filter is confusing I think. One might think "reset" will
reset everything. Is it hard to do a checkbox? Or an on/off toggle or
on/off slider? Thanks!

I can toggle the data attribute

**Comment by mashcode** [comment]
I reverted to the old filter and changed the Contact icon to text. The addthis plugin has classes that seem to suggest it can be made to work on mobile?

**Comment by schmiani** [comment]
I don't think we need the addthis on mobile, as one has the built in sharing options, at least on the iphone? I think this is fine right now and thanks for adding the email address for contact!

**Pull request merged**
